nearby_clinics_dict = {
    "Addison": ["BT", "BL", "BR Village", "DG Main St", "York", "GE", "GE 854", "Clay", "AHR1300", "Archer Lemont",
                "Lisle", "LOM", "CG", "HS", "Iroquois", "WASH", "Westmont", "Westmont Ogden", "PASQ", "WTN",
                "Rt 56 WTN", "WDG"],
    "Marketplace": ["Ogden", "Aurora Westbrook", "Weber Rd", "BR Village", "DG Main St", "York", "GE", "GE 854",
                    "North Creek", "Archer Lemont", "Lisle", "Lockport", "LOM", "CG", "HS", "Iroquois", "MMO NPV",
                    "Saddlewood", "WASH", "RT 59", "Division", "SW 102", "Westmont", "Westmont Ogden", "PASQ", "WTN",
                    "Rt 56 WTN", "WDG"],
    "Ogden": ["Marketplace", "Aurora Westbrook", "Weber Rd", "Lisle", "LOM", "CG", "HS", "Iroquois", "MMO NPV",
              "Saddlewood", "WASH", "RT 59", "Division", "WTN", "Rt 56 WTN", "WDG"],
    "Aurora Westbrook": ["Marketplace", "Ogden", "Weber Rd", "DG Main St", "GE 854", "Lisle", "LOM", "CG", "HS",
                         "Iroquois", "MMO NPV", "Saddlewood", "WASH", "RT 59", "Division", "Westmont", "Westmont Ogden",
                         "PASQ", "WTN", "Rt 56 WTN", "WDG"],
    "BT": ["Addison", "BL", "York", "GE", "GE 854", "AHR1300", "LOM", "CG", "Iroquois", "MMO NPV", "WTN", "Rt 56 WTN"],
    "BL": ["Addison", "BT", "DG Main St", "York", "GE", "GE 854", "AHR1300", "Lisle", "LOM", "CG", "Westmont",
           "Westmont Ogden", "PASQ", "WTN", "Rt 56 WTN", "WDG"],
    "Weber Rd": ["Marketplace", "Ogden", "Aurora Westbrook", "BR Village", "DG Main St", "Joliet", "North Creek",
                 "Archer Lemont", "Lisle", "Lockport", "CG", "HS", "Iroquois", "MMO NPV", "Saddlewood", "WASH", "RT 59",
                 "Division", "SW 102", "Rt 56 WTN", "WDG"],
    "Burbank": ["BR Village", "Oak Lawn", "PASQ"],
    "BR Village": ["Addison", "Marketplace", "Weber Rd", "Burbank", "DG Main St", "York", "GE", "GE 854", "Clay",
                   "AHR1300", "Archer Lemont", "Lisle", "Lockport", "LOM", "CG", "HS", "Iroquois", "WASH", "Oak Lawn",
                   "RT 59", "Division", "SW 102", "SH", "Westmont", "Westmont Ogden", "PASQ", "Rt 56 WTN", "WDG"],
    "DG Main St": ["Addison", "Marketplace", "Aurora Westbrook", "BL", "Weber Rd", "BR Village", "York", "GE", "GE 854",
                   "Clay", "AHR1300", "Archer Lemont", "Lisle", "Lockport", "LOM", "CG", "HS", "Iroquois", "MMO NPV",
                   "WASH", "Westmont", "Westmont Ogden", "PASQ", "WTN", "Rt 56 WTN", "WDG"],
    "York": ["Addison", "Marketplace", "BT", "BL", "BR Village", "DG Main St", "GE", "GE 854", "Clay", "AHR1300",
             "Lisle", "LOM", "Westmont", "Westmont Ogden", "PASQ", "Rt 56 WTN", "WDG"],
    "GE": ["Addison", "CG", "Marketplace", "BT", "BL", "BR Village", "DG Main St", "York", "GE 854", "AHR1300", "Lisle",
           "LOM", "Iroquois", "Westmont", "Westmont Ogden", "WTN", "Rt 56 WTN", "WDG"],
    "GE 854": ["Addison", "Marketplace", "Aurora Westbrook", "BT", "BL", "BR Village", "DG Main St", "York", "GE",
               "Clay", "AHR1300", "Lisle", "LOM", "CG", "Iroquois", "Westmont", "Westmont Ogden", "PASQ", "WTN",
               "Rt 56 WTN", "WDG"],
    "Clay": ["Addison", "BR Village", "DG Main St", "York", "GE 854", "Lisle", "LOM", "Westmont", "Westmont Ogden",
             "PASQ"],
    "AHR1300": ["Addison", "BT", "BL", "BR Village", "DG Main St", "York", "GE", "GE 854", "Lisle", "LOM", "WTN"],
    "Joliet": ["Weber Rd", "North Creek", "Division", "SW 102"],
    "North Creek": ["Marketplace", "Weber Rd", "Joliet", "RT 59", "Division", "SW 102"],
    "Archer Lemont": ["Addison", "Marketplace", "Weber Rd", "BR Village", "DG Main St", "Lisle", "Lockport", "LOM",
                      "New Lenox", "Westmont Ogden", "WDG"],
    "Lisle": ["Addison", "Marketplace", "Ogden", "Aurora Westbrook", "BL", "Weber Rd", "Weber Rd", "BR Village",
              "DG Main St", "York", "GE", "GE 854", "Clay", "AHR1300", "Archer Lemont", "Lockport", "LOM", "CG", "HS",
              "Iroquois", "MMO NPV", "WASH", "Westmont", "Westmont Ogden", "PASQ", "WTN", "Rt 56 WTN", "WDG"],
    "Lockport": ["BR Village", "DG Main St", "Archer Lemont", "Lisle", "New Lenox", "Orland Hills", "Division", "WDG"],
    "LOM": ["Addison", "Marketplace", "Ogden", "Aurora Westbrook", "BT", "BL", "BR Village", "DG Main St", "York", "GE",
            "GE 854", "Clay", "AHR1300", "Archer Lemont", "Lisle", "CG", "Iroquois", "Westmont", "Westmont Ogden",
            "PASQ", "WTN", "Rt 56 WTN", "WDG"],
    "CG": ["Addison", "Marketplace", "Ogden", "Aurora Westbrook", "BT", "BL", "Weber Rd", "BR Village", "DG Main St",
           "GE 854", "Lisle", "LOM", "HS", "Iroquois", "MMO NPV", "Saddlewood", "WASH", "Westmont", "Westmont Ogden",
           "WTN", "Rt 56 WTN", "WDG"],
    "HS": ["Addison", "Marketplace", "Ogden", "Aurora Westbrook", "Weber Rd", "BR Village", "DG Main St", "Lisle", "CG",
           "Iroquois", "MMO NPV", "Saddlewood", "WASH", "RT 59", "Rt 56 WTN", "WDG"],
    "Iroquois": ["Addison", "Marketplace", "Ogden", "Aurora Westbrook", "BT", "Weber Rd", "BR Village", "DG Main St",
                 "GE", "GE 854", "Lisle", "LOM", "CG", "HS", "MMO NPV", "Saddlewood", "WASH", "Westmont",
                 "Westmont Ogden", "PASQ", "WTN", "Rt 56 WTN", "WDG"],
    "MMO NPV": ["Marketplace", "Ogden", "Aurora Westbrook", "BT", "Weber Rd", "DG Main St", "Lisle", "CG", "HS",
                "Iroquois", "Saddlewood", "WASH", "RT 59", "WDG"],
    "Saddlewood": ["Marketplace", "Ogden", "Aurora Westbrook", "Weber Rd", "CG", "HS", "Iroquois", "MMO NPV", "WASH",
                   "RT 59", "Division", "WDG"],
    "WASH": ["Addison", "Marketplace", "Ogden", "Aurora Westbrook", "Weber Rd", "BR Village", "DG Main St", "Lisle",
             "CG", "HS", "Iroquois", "MMO NPV", "Saddlewood", "RT 59", "WTN", "Rt 56 WTN", "WDG"],
    "New Lenox": ["Archer Lemont", "Lockport", "SH"],
    "Oak Lawn": ["Burbank", "BR Village"],
    "Orland Hills": ["Lockport", "SH"],
    "RT 59": ["Marketplace", "Ogden", "Aurora Westbrook", "Weber Rd", "BR Village", "North Creek", "HS", "MMO NPV",
              "Saddlewood", "WASH", "Division", "SW 102"],
    "Division": ["Marketplace", "Ogden", "Aurora Westbrook", "Weber Rd", "BR Village", "Joliet", "North Creek",
                 "Lockport", "Saddlewood", "RT 59", "SW 102"],
    "SW 102": ["Marketplace", "Weber Rd", "BR Village", "Joliet", "North Creek", "RT 59", "Division"],
    "SH": ["BR Village", "New Lenox", "Orland Hills"],
    "Westmont": ["Addison", "Marketplace", "Aurora Westbrook", "BL", "BR Village", "DG Main St", "York", "GE", "GE 854",
                 "Clay", "Lisle", "LOM", "CG", "Iroquois", "Westmont Ogden", "PASQ", "Rt 56 WTN", "WDG"],
    "Westmont Ogden": ["Addison", "Marketplace", "Aurora Westbrook", "BL", "BR Village", "DG Main St", "York", "GE",
                       "GE 854", "Clay", "Archer Lemont", "Lisle", "LOM", "CG", "Iroquois", "Westmont", "PASQ", "WTN",
                       "Rt 56 WTN", "WDG"],
    "PASQ": ["Addison", "Marketplace", "Aurora Westbrook", "BL", "Burbank", "BR Village", "DG Main St", "York",
             "GE 854", "Clay", "Lisle", "LOM", "Iroquois", "Westmont", "Westmont Ogden", "Rt 56 WTN", "WDG"],
    "WTN": ["Addison", "Marketplace", "Ogden", "Aurora Westbrook", "BT", "BL", "DG Main St", "GE", "GE 854", "AHR1300",
            "Lisle", "LOM", "CG", "Iroquois", "WASH", "Westmont Ogden", "Rt 56 WTN", "WDG"],
    "Rt 56 WTN": ["Addison", "Marketplace", "Ogden", "Aurora Westbrook", "BT", "BL", "Weber Rd", "BR Village",
                  "DG Main St", "York", "GE", "GE 854", "Lisle", "LOM", "CG", "HS", "Iroquois", "WASH", "Westmont",
                  "Westmont Ogden", "PASQ", "WTN", "WDG"],
    "WDG": ["Addison", "Marketplace", "Ogden", "Aurora Westbrook", "BL", "Weber Rd", "BR Village", "DG Main St", "York",
            "GE", "GE 854", "Archer Lemont", "Lisle", "Lockport", "LOM", "CG", "HS", "Iroquois", "MMO NPV",
            "Saddlewood", "WASH", "Westmont", "Westmont Ogden", "PASQ", "WTN", "Rt 56 WTN"]
}

matching_requests_dict = {
    "Needs a Tech": "Has a Tech to Spare",
    "CHas a Tech to Spare": "Needs a Tech",
    "Needs to Relocate a Therapist": "Can Accommodate a Therapist",
    "Can Accommodate a Therapist": "Needs to Relocate a Therapist"
}
